#!/usr/bin/with-contenv bash
set -e

if [ -n MYSQL_ROOT_PASSWORD ]
then
	PASSWD="'$MYSQL_ROOT_PASSWORD'"
	pkill -9 mysqld_safe;pkill -9 mysqld_safe;pkill -9 mariadbd
	/usr/bin/mariadbd-safe --skip-grant-tables --skip-networking &
cat > mysql << EOF
USE mysql;
FLUSH PRIVILEGES;
SET PASSWORD FOR root@'localhost' = PASSWORD($PASSWD);
UPDATE mysql.user SET password=PASSWORD($PASSWD) WHERE user='root';"
FLUSH PRIVILEGES;
EOF
#UPDATE user SET plugin='unix_socket' WHERE user='root' and host='localhost';
	/usr/bin/pkill -9 mariadbd-safe
	/usr/bin/pkill -9 mariadbd

fi
